**The first thing to do is to run Creator.py to setup the dataset. First specify the options**


In [6]:
import numpy as np
# The Name of the Dataset
Name = "Guns/Guns-100-inv-daul"

# Frequency Array
Frequencies=np.array([119.25,178.875,238.5,298.125,357.75,477,596.25,715.5,954,1192.5,1431,1908,2385,2862,3816,4770,5724,7632,9540,12402,16218,20988,26712,34344,43884,57240,73458,95400])
Frequencies = Frequencies*6.28 #Convert to rad/s'
#Frequencies=np.logspace(2,8,150)

# Classes to Include
Classes = ["Guns"]
#
# Global number of results
# Coin Problem
extend_results = 'global_obj'

# Number of secondary results if 'global_obj'

#Coin Problem`
Num_Results = 100

# Classes if 'global_class' or 'classwise'
class_split=[]

# Name each of the classes this is done in order
class_names = []

# Number of results if 'global_class'
Num_Results_class = []


# (int) Number of results per class results per class if 'classwise'
class_num_results = []

#Labeler False,'Classwise', 'Objectwise'
Label_Data = 'Objectwise'
Name_Objects = True

#(dictionary) name the objects as you wish them to appear in the classificaiton


Object_Names_dictionary ={"Short_Gun_steel":r"Short_Pistol_St.1/St.3", 
                          "Medium_Gun_steel":r"Pistol_St.1/St.3",
                          "Long_Gun_steel":r"Rifle_St.1/St.3",
                          "Dual_Short_Gun_steel":r"Dual_Short_Pistol_St.1/St.3", 
                          "Dual_Medium_Gun_steel":r"Dual_Pistol_St.1/St.3",
                          "Dual_Long_Gun_steel":r"Dual_Rifle_St.1/St.3",
                          "Short_Normal_steel":r"Short_Pistol_St.2/St.3",
                          "Medium_Normal_steel":r"Pistol_St.2/St.3",
                          "Long_Normal_steel":r"Rifle_St.2/St.3",
                          "Dual_Short_Normal_steel":r"Dual_Short_Pistol_St.2/St.3",
                          "Dual_Medium_Normal_steel":r"Dual_Pistol_St.2/St.3",
                          "Dual_Long_Normal_steel":r"Dual_Rifle_St.2/St.3"}
                          

Name_Order = ["Short_Gun_steel", 
                  "Medium_Gun_steel",
                  "Long_Gun_steel",
              "Dual_Short_Gun_steel", 
                  "Dual_Medium_Gun_steel",
                  "Dual_Long_Gun_steel",
                  "Short_Normal_steel",
                  "Medium_Normal_steel",
                  "Long_Normal_steel",
              "Dual_Short_Normal_steel",
                  "Dual_Medium_Normal_steel",
                  "Dual_Long_Normal_steel"]

#How to scale
Scale_type = 'Global'

#Which file (This is not currently used)
Scale_File = 'Coin_DataSet.csv'


#Alpha scale
Alpha_scale = 0.84

#Sigma scale
Sigma_scale = 12.5

# Path Name for where the class data is stored
Class_dir = "Classes_Paul"

# Create a dictionary of these settings
Creator_Settings = {"Name":Name,"Frequencies":Frequencies,"Classes":Classes,"extend_results":extend_results,"Num_Results":Num_Results,#
                    "class_split":class_split,"class_names":class_names,"Num_Results_class":Num_Results_class,"class_num_results":class_num_results,\
                    "Label_Data":Label_Data,"Name_Objects":Name_Objects,"Object_Names_dictionary":Object_Names_dictionary,"Name_Order":Name_Order,\
                    "Scale_type":Scale_type,"Scale_File":Scale_File,"Alpha_scale":Alpha_scale,"Sigma_scale":Sigma_scale, "Class_dir":Class_dir}

In [7]:
# Run the Creator script
from Creator import *
#DataSet_Name=Creator(Name,Frequencies,Classes,extend_results,Num_Results,class_split,class_names,\
#            Num_Results_class,class_num_results,Label_Data, Name_Objects,Object_Names_dictionary,Name_Order,Scale_type,Scale_File,\
#            Alpha_scale,Sigma_scale)
DataSet_Name=Creator(Creator_Settings)

The folder path to the dataset is: Guns/Guns-100-inv-daul_Al_0.84_Sig_12.5
Class type is a list
Medium_Normal_steel
Short_Gun_steel
Short_Normal_steel
Long_Gun_steel
Medium_Gun_steel
Dual_Short_Normal_steel
Dual_Long_Gun_steel
Long_Normal_steel
Dual_Medium_Gun_steel
Dual_Short_Gun_steel
Dual_Medium_Normal_steel
Dual_Long_Normal_steel
(1200, 28) 28


In [8]:
# This is the dataset name to be used with the classifier

#DataSet_Name="British-Coins-Updated-1p-2p/Coins-100_Al_0.84_Sig_12.5"
#DataSet_Name="British-Coins-Updated-1p-2p/Coins-100_Al_0.84_Sig_12.5"
print(DataSet_Name)

Guns/Guns-100-inv-daul_Al_0.84_Sig_12.5


**The next part involves running the actual classifier. This is done using Trainer_PDL.py**

In [9]:
# Option to load external testing data from disk. Requires that external_file_loader.py be run first.
Load_External_Data = False 
# Option to plot comparison figures between the input array of simulated data and the external test data.
# Currently only supported for a single class test set.
Plot_Comparison_Figures = True
# Option to additionally save to disk: the model for each bootstrap iteration, the normalisation coefficients for each,
# bootstrap iteration, and the input array for each model, Used for debugging.
Full_Save = False

# Option to use SVD to reduce the number of features
Reduce_Features = False

#Model to be used
#Optional models 'LogisticRegression', 'SVM', 'DecisionTree', 'RandomForest', 'GradientBoost', 'MLP','MLP,(n1,n2,...,nn)'
Models_to_run = ['LogisticRegression']#,'SVM','GradientBoost']

#Features
Features = ['AngleRtildeI']#['Pri1','Pri2','Pri3']#['AngleRtildeI']#
# Features = ['Eig1', 'Eig2', 'Eig3']
#(list) list of features to be used options:
#'Eig1','Eig2','Eig3','Pri1','Pri2','Pri3','Dev2','Dev3','Com','AngleRtildeI'
#Eigenvalues, Principal invarients, Deviatoric invarients, Comutator, Angle between Rtilde and I

#How many times would you like to train the model
Bootstrap_Repetitions = 1
#(int) how many times to train the model to obtain an average accuracy

# use default levels of SNR
SNR_array=[]

# Make plot of first two reduced invairants
Plot_Principal_Componenets = False

Trainer_Settings = {"DataSet_Name": DataSet_Name, "Load_External_Data":Load_External_Data, "Plot_Comparison_Figures":Plot_Comparison_Figures,\
                   "Full_Save": Full_Save, "Reduce_Features":Reduce_Features, "Models_to_run": Models_to_run, "Features":Features, #
                    "Bootstrap_Repetitions": Bootstrap_Repetitions, "SNR_array": SNR_array, "Plot_Principal_Componenets": Plot_Principal_Componenets }

In [ ]:
from Trainer_PDL import *

#main(DataSet_Name,Load_External_Data,Plot_Comparison_Figures,Full_Save,Reduce_Features,Models_to_run,Features,Bootstrap_Repetitions)
main(Trainer_Settings)

Noise level =  5
(1200, 504)
(1200, 30) (1200, 28)
Data [[0.00059428 0.00054747 0.00050917 ... 0.02277822 0.02026809 0.01836444]
 [0.00059428 0.00054747 0.00050917 ... 0.02110198 0.01907812 0.01738714]
 [0.00059428 0.00054747 0.00050917 ... 0.02369585 0.02088707 0.01883588]
 ...
 [0.00094811 0.00081616 0.00071006 ... 0.02954796 0.02648533 0.02459272]
 [0.00094811 0.00081616 0.00071006 ... 0.02673518 0.02480558 0.02359143]
 [0.00094811 0.00081616 0.00071006 ... 0.02639482 0.02460479 0.02346121]]
to here
LogisticRegression


/home/paul/Coding/MPT_Classifier_Testing/MPT_Classifier/Functions/Plot_comparison_features.py:177: UserWarning: 
The palette list has fewer values (10) than needed (12) and will cycle, which may produce an uninterpretable plot.
  total_lineplot = sns.lineplot(data=internal_dataframe, x='omega',


Noise level =  10
(1200, 504)
(1200, 30) (1200, 28)
Data [[0.00059428 0.00054747 0.00050917 ... 0.02277822 0.02026809 0.01836444]
 [0.00059428 0.00054747 0.00050917 ... 0.02110198 0.01907812 0.01738714]
 [0.00059428 0.00054747 0.00050917 ... 0.02369585 0.02088707 0.01883588]
 ...
 [0.00094811 0.00081616 0.00071006 ... 0.02954796 0.02648533 0.02459272]
 [0.00094811 0.00081616 0.00071006 ... 0.02673518 0.02480558 0.02359143]
 [0.00094811 0.00081616 0.00071006 ... 0.02639482 0.02460479 0.02346121]]
to here
LogisticRegression


/home/paul/Coding/MPT_Classifier_Testing/MPT_Classifier/Functions/Plot_comparison_features.py:177: UserWarning: 
The palette list has fewer values (10) than needed (12) and will cycle, which may produce an uninterpretable plot.
  total_lineplot = sns.lineplot(data=internal_dataframe, x='omega',


Noise level =  15
(1200, 504)
(1200, 30) (1200, 28)
Data [[0.00059428 0.00054747 0.00050917 ... 0.02277822 0.02026809 0.01836444]
 [0.00059428 0.00054747 0.00050917 ... 0.02110198 0.01907812 0.01738714]
 [0.00059428 0.00054747 0.00050917 ... 0.02369585 0.02088707 0.01883588]
 ...
 [0.00094811 0.00081616 0.00071006 ... 0.02954796 0.02648533 0.02459272]
 [0.00094811 0.00081616 0.00071006 ... 0.02673518 0.02480558 0.02359143]
 [0.00094811 0.00081616 0.00071006 ... 0.02639482 0.02460479 0.02346121]]
to here
LogisticRegression


/home/paul/Coding/MPT_Classifier_Testing/MPT_Classifier/Functions/Plot_comparison_features.py:177: UserWarning: 
The palette list has fewer values (10) than needed (12) and will cycle, which may produce an uninterpretable plot.
  total_lineplot = sns.lineplot(data=internal_dataframe, x='omega',


Noise level =  20
(1200, 504)
(1200, 30) (1200, 28)
Data [[0.00059428 0.00054747 0.00050917 ... 0.02277822 0.02026809 0.01836444]
 [0.00059428 0.00054747 0.00050917 ... 0.02110198 0.01907812 0.01738714]
 [0.00059428 0.00054747 0.00050917 ... 0.02369585 0.02088707 0.01883588]
 ...
 [0.00094811 0.00081616 0.00071006 ... 0.02954796 0.02648533 0.02459272]
 [0.00094811 0.00081616 0.00071006 ... 0.02673518 0.02480558 0.02359143]
 [0.00094811 0.00081616 0.00071006 ... 0.02639482 0.02460479 0.02346121]]
to here
LogisticRegression


/home/paul/Coding/MPT_Classifier_Testing/MPT_Classifier/Functions/Plot_comparison_features.py:177: UserWarning: 
The palette list has fewer values (10) than needed (12) and will cycle, which may produce an uninterpretable plot.
  total_lineplot = sns.lineplot(data=internal_dataframe, x='omega',


Noise level =  40
(1200, 504)
(1200, 30) (1200, 28)
Data [[0.00059428 0.00054747 0.00050917 ... 0.02277822 0.02026809 0.01836444]
 [0.00059428 0.00054747 0.00050917 ... 0.02110198 0.01907812 0.01738714]
 [0.00059428 0.00054747 0.00050917 ... 0.02369585 0.02088707 0.01883588]
 ...
 [0.00094811 0.00081616 0.00071006 ... 0.02954796 0.02648533 0.02459272]
 [0.00094811 0.00081616 0.00071006 ... 0.02673518 0.02480558 0.02359143]
 [0.00094811 0.00081616 0.00071006 ... 0.02639482 0.02460479 0.02346121]]
to here
LogisticRegression


/home/paul/Coding/MPT_Classifier_Testing/MPT_Classifier/Functions/Plot_comparison_features.py:177: UserWarning: 
The palette list has fewer values (10) than needed (12) and will cycle, which may produce an uninterpretable plot.
  total_lineplot = sns.lineplot(data=internal_dataframe, x='omega',
